### ISSUE TITLE
Razorpay integration Frontend

### ISSUE THREAD

**Issue by Jenin82** [gtech-mulearn/mulearn#1083]

**Comment by Jenin82** [comment]
@bijomathewjose 

If you want to integrate with only the frontend, you can use the Razorpay Payment Button to accept payments on your website or blog. The Payment Button is a simple and easy way to add payment functionality without the need for a backend integration.

To integrate with only the frontend, follow these steps:

1. Sign up for a Razorpay account if you haven't already done so.
2. Generate the API keys from the Razorpay Dashboard. You will need the API key and the API secret key for the frontend integration.
3. Add the Razorpay JavaScript library to your website. You can find the library and the integration code snippet on the Razorpay GitHub repository.
4. Add the integration code snippet after the `deviceready` event in your HTML file.
5. Customize the Payment Button according to your requirements. You can specify the amount, currency, and other parameters for the payment.
6. Handle the payment response using the Razorpay API. You can use the `razorpay_payment_id` and other parameters to verify the payment and update your frontend accordingly.

Please note that if you want to perform any server-side operations or access sensitive information, such as generating order IDs or updating the payment status, you will need a backend integration. The frontend integration is suitable for basic payment acceptance and handling the payment response on the client-side.

For more details and code examples, you can refer to the Razorpay documentation and the sample code on GitHub.

- Razorpay Documentation: [Frontend Integration](https://razorpay.com/docs/payment-gateway/web-integration/standard/)
- Razorpay GitHub Repository: [Sample Code](https://github.com/razorpay/razorpay-cordova-sample-app/tree/master/)

**Comment by Jenin82** [comment]
You don't need backend for basic donation feature

**Comment by bijomathewjose** [comment]
# Razorpay Configuration 

## Step 1
https://dashboard.razorpay.com/app/paymentpages/
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/7d03d0e1-875c-465a-838e-42657174fbc9)

## Step 2
- Click on "Select Payment Page" button on bottom left of the page
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/b1f7ecaa-4174-40d1-86b4-b99c76d8491c)

## Step 3
- Add Relevant Details 
- Click "Create and Publish Page" in the top right corner of the page
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/203c8682-2413-470a-827c-ad9e7f6152a4)

## Step 4
- Copy the "Page Url" 
- Add this url as env variable "REACT_APP_DONATION_LINK" to the website
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/d3f2c176-496c-4c10-9606-2f09fc665804)

## Step 5
- Track the transaction in the dashboard ,payment page
- https://dashboard.razorpay.com/app/paymentpages/

**Comment by viraka** [comment]
Completed Basic Functionality on the Frontend

![Image](https://github.com/gtech-mulearn/mulearn/assets/14145817/37b19d1b-5a8b-4044-9b50-7c3fd40e4296)



![Image](https://github.com/gtech-mulearn/mulearn/assets/14145817/7a2bd7ba-69bd-4dc2-8559-16e68a821212)
