### ISSUE TITLE
InternTask2_Shreerag Namboothir K H_04

### ISSUE THREAD

**Issue by shreeragkh** [gtech-mulearn/mulearn#1307]
### Describe your issue

while clicking on "Terms and condition" in footer section, it does not redirection to "Terms and condition" webpage

### Steps to reproduce

1. Launch your browser
2. Enter this Link in your browser "https://learn.mulearn.org/challenges"
3. Click "Terms and condition" in footer section

### What was the expected result?

The expected result is, while clicking the  "Terms and condition" in footer section it should redirect to "Terms and condition" webpage

### Put here any screenshots or videos (optional)

![Screenshot from 2024-05-07 00-18-36](https://github.com/gtech-mulearn/mulearn/assets/134316200/3cbf7cd0-95e5-4ed2-bbd3-8e9ced98849c)

### Would you like to work on this issue?

None

**Comment by vidhya-vjkumar** [comment]
Duplicate issue. Issue no.: #1129
