### ISSUE TITLE
InternTask1_[Abin Francis]_1

### ISSUE THREAD

**Issue by abinfranci5** [gtech-mulearn/mulearn#1358]
### Describe your issue

The logo of X (formally known as twitter) logo is still bird at the bottom of home page

### Steps to reproduce

Go to home page
scroll down
find the social media links logo

### What was the expected result?

I expected new logo of X would be there

### Would you like to work on this issue?

None

**Comment by vidhya-vjkumar** [comment]
Duplicate issue. Issue no.: #1368
