### ISSUE TITLE
Weekly Event Page - ISR

### ISSUE THREAD

**Issue by Ansanjohny** [gtech-mulearn/mulearn#1436]
### Describe your issue

When we click on inspiration station radio Check it out option , it shows infinite number of api calls

### Steps to reproduce

1. Go to [events](https://mulearn.org/events)
2. Click on Check it out option of inspiration station radio
3. open network tab and  refresh

### What was the expected result?

Expected result is only one api call for inspiration station radio

### Put here any screenshots or videos (optional)

![image](https://github.com/gtech-mulearn/mulearn/assets/97939405/a4ed50eb-7a01-4e3a-a27e-1e9a2edbc793)

### Would you like to work on this issue?

None

**Comment by awindsr** [comment]
fixed the issue

**Comment by Ansanjohny** [comment]
@awindsr Still the issue exist 
![image](https://github.com/gtech-mulearn/mulearn/assets/97939405/777c69d9-e1ec-4d49-b573-feb3d6d4b53a)

**Comment by Jenin82** [comment]
@viraka Why is this in review, is the bug already fixed ? 
We put issues in review when the bug is fixed and ready for testing

**Comment by viraka** [comment]
@Jenin82 My bad, we encountered the build issue while reviewing the pr made for issue. Will take care of moving it to required place.

**Comment by GeorgeET15** [comment]
Hi, can I work on this issue.

**Comment by Jenin82** [comment]
@GeorgeET15 sure go ahead
