### ISSUE TITLE
events-isr, smt,open mic, mulearn mentor connect-link issue

### ISSUE THREAD

**Issue by shreeragkh** [gtech-mulearn/mulearn#1441]
### Describe your issue

When clicking on instagram icon present in footer section, it does not redirecting to official instagram account of mulearn 

### Steps to reproduce

1. open "https://mulearn.org/events"
2. Go to footer section
3. click instagram icon present in footer section
4. When clicking on the icon it does not redirecting to offcial instagram account of mulearn
5. All the related subpages of events like isr, smt, open mic, mulearn mentor connect have same issue

### What was the expected result?

The expected result is, when clicking on instgram icon it should redirect to official instagram account of mulearn 

### Put here any screenshots or videos (optional)
![Screenshot from 2024-05-14 12-23-30](https://github.com/gtech-mulearn/mulearn/assets/134316200/c2978272-d49b-496c-b12a-f18bf7ea7d76)

### Would you like to work on this issue?

None

**Comment by arjuncvinod** [comment]
can i take up this issue
