### ISSUE TITLE
Mulearn Home Page - Infinite API calls 

### ISSUE THREAD

**Issue by Ansanjohny** [gtech-mulearn/mulearn#1443]
### Describe your issue

When open home page infinite number of api calls in network tab

### Steps to reproduce

1. Go to [Mulearn](https://mulearn.org/)
2. Open network tab and check api calls - In network tabs infinite number of api calls 

### What was the expected result?

Only one api call for  that particular  data

### Put here any screenshots or videos (optional)

![image](https://github.com/gtech-mulearn/mulearn/assets/97939405/734ab54a-4da9-4420-b2ad-4f30fccae7d7)

### Would you like to work on this issue?

None

**Comment by GeorgeET15** [comment]
Can I work on this issue?

**Comment by Jenin82** [comment]
@GeorgeET15 what is the status of this issue ?

**Comment by GeorgeET15** [comment]
Reading cookie in cross-site context will be blocked. This is causing the infinite api calls while trying to embed yt videos.

**Comment by GeorgeET15** [comment]
I'm still trying to find a way to solve this

**Comment by Jenin82** [comment]
@GeorgeET15 if you need help don't hesitate to ask 👍
