### ISSUE TITLE
InterestGrouppage-Android development mentor profile picture shows error-issue 10

### ISSUE THREAD

**Issue by muraliaiswarya** [gtech-mulearn/mulearn#1460]
### Describe your issue

when observing the mentor details in Android development interest group, Amrit sanjeev profile pic is missing

### Steps to reproduce

1.Launch Browser
2.enter URL"https://learn.mulearn.org/"
3.click on checkout group of web and mobile app development
4.click on checkout group of Android development
5.Scroll to Mentor details Amrit Sanjeev and observe the profile picture

### What was the expected result?

should display the profile picture in its full form
Actual: displayed an error in the place of profile picture

### Put here any screenshots or videos (optional)

![image](https://github.com/gtech-mulearn/mulearn/assets/157092697/0ce3d371-3e1e-40bf-aad7-bc740f329633)

### Would you like to work on this issue?

None

**Comment by Ansanjohny** [comment]
Duplicate issue . Issue Number #1457
