### ISSUE TITLE
InterestGrouppage-cyber security mentor details-Issue 12

### ISSUE THREAD

**Issue by muraliaiswarya** [gtech-mulearn/mulearn#1463]
### Describe your issue

when observing the mentor details in cyber security interest group, Rejah Rehim and Nash N Sulthan profile pic is missing

### Steps to reproduce

1.Launch Browser
2.enter URL"https://learn.mulearn.org/"
3.click on checkout group of web and mobile app development
4.click on checkout group of cyber security
5.Scroll to Mentor details Rejah Rehim and Nash N Sulthan ,observe the profile picture

### What was the expected result?

should display the profile picture in its full form
Actual: displayed an error in the place of profile picture

### Put here any screenshots or videos (optional)

![image](https://github.com/gtech-mulearn/mulearn/assets/157092697/b9c8e536-3a69-4291-9739-a584157ebe9d)

### Would you like to work on this issue?

None

**Comment by Ansanjohny** [comment]
Duplicate issue . Issue Number #1457

**Comment by Ansanjohny** [comment]
Duplicate issue . Issue Number #1457
