### ISSUE TITLE
InterestGrouppage-Innovation and Entrepreneusrship -Product Management-Issue 13

### ISSUE THREAD

**Issue by muraliaiswarya** [gtech-mulearn/mulearn#1464]
### Describe your issue

when observing the mentor details in Android development interest group, Vineesh U S and Aravind Muraleedharan profile pic are missing

### Steps to reproduce

1.Launch Browser
2.enter URL"https://learn.mulearn.org/"
3.click on checkout group of Innovation and Entrepreneusrship
4.click on checkout group of Product Management
5.Scroll to Mentor details Vineesh U S and Aravind Muraleedharan and observe the profile picture

### What was the expected result?

should display the profile picture in its full form
Actual: displayed an error in the place of profile picture

### Put here any screenshots or videos (optional)

![Screenshot 2024-05-15 215750](https://github.com/gtech-mulearn/mulearn/assets/157092697/192d34d5-7d1b-4704-8da8-dda5c8d1c9cb)

### Would you like to work on this issue?

None

**Comment by Ansanjohny** [comment]
Duplicate issue . Issue Number #1457
