### ISSUE TITLE
InterestGrouppage-Innovation & Entrepreneurship- mentor profile picture shows error-issue 14

### ISSUE THREAD

**Issue by muraliaiswarya** [gtech-mulearn/mulearn#1465]
### Describe your issue

when observing the mentor details in Innovation & Entrepreneurship interest group, Deepu S Nath profile pic are missing

### Steps to reproduce

1.Launch Browser
2.enter URL"https://learn.mulearn.org/"
3.click on checkout group of Innovation and Entrepreneusrship
4.click on checkout group of Innovation & Entrepreneurship
5.Scroll to Mentor details Deepu S Nath  and observe the profile picture

### What was the expected result?

should display the profile picture in its full form
Actual: displayed an error in the place of profile picture

### Put here any screenshots or videos (optional)

![image](https://github.com/gtech-mulearn/mulearn/assets/157092697/d2b1f045-90e0-4705-a788-ec5374b5eeda)

### Would you like to work on this issue?

None

**Comment by Ansanjohny** [comment]
Duplicate issue . Issue Number #1457
