### ISSUE TITLE
Infinite API Calls in Saltmangotree Page

### ISSUE THREAD

**Issue by Ansanjohny** [gtech-mulearn/mulearn#1479]
### Describe your issue

When open the saltmangotree page, in network tab infinite number of api calls

### Steps to reproduce

1. Go to [saltmangotree](https://mulearn.org/events/saltmangotree)
2. Open network  tab 
3. In network tab we can see the infinite number of api calls

### What was the expected result?

To call one api

### Put here any screenshots or videos (optional)

![image](https://github.com/gtech-mulearn/mulearn/assets/97939405/0d0986b9-4846-4854-8172-cdb39cd08281)

### Would you like to work on this issue?

None

**Comment by GeorgeET15** [comment]
Can I work on this issue

**Comment by GeorgeET15** [comment]
I had solved this issue
