### ISSUE TITLE
mu-dev-500-login page

### ISSUE THREAD

**Issue by vidhya-vjkumar** [gtech-mulearn/mulearn#1483]
### Describe your issue

When redirected to the login page after logout or while accessing the login page otherwise, an Internal server error occurs (Status: 500, type: ping).

### Steps to reproduce

1. Go to the dev server login page or logout from a logged in profile in the dev server

### Put here any screenshots or videos (optional)

![Screenshot (333)](https://github.com/gtech-mulearn/mulearn/assets/106170027/797a4441-94f4-459d-8d45-9090ede52ee6)
![Screenshot (334)](https://github.com/gtech-mulearn/mulearn/assets/106170027/f2166eeb-d666-4862-aed6-60c8681a640a)

### Would you like to work on this issue?

None

**Comment by Ansanjohny** [comment]
In network tab select "Fetch/XHR"  , then recheck this issue @vidhya-vjkumar
