### ISSUE TITLE
Wadhwani Api Loading Issue

### ISSUE THREAD

**Issue by viraka** [gtech-mulearn/mulearn#1509]
### Describe your issue

The Wadhwani Module requires a toast to be palced in the api. Unfortunately the api calls take some time and page seems unresponsive to the user . Preferably set a loader while entering wadhwani and then put a toast loading when redirecting to them.

### Steps to reproduce

1. Go to https://dev-app-mulearn.vercel.app/dashboard/wadhwani

Youll see the issue once you load in and also when you try to click the cards aswell.

![Image](https://github.com/gtech-mulearn/mulearn/assets/14145817/91558147-4299-4709-b893-12c56aaa2c2f)

### What was the expected result?

Need a Loader and loading toast to make user feel the site is responsive.

### Would you like to work on this issue?

None

**Comment by arjuncvinod** [comment]
can i take up this issue
