### ISSUE TITLE
mu-dev- Task Management - Tasks - Negative usage count

### ISSUE THREAD

**Issue by vidhya-vjkumar** [gtech-mulearn/mulearn#1535]
### Describe your issue

Negative values in usage count is being accepted.

### Steps to reproduce

1. Go to https://dev-app-mulearn.vercel.app/dashboard/tasks
2. Sort usage count in ascending order. Tasks with negative usage count will be visible. Or try creating a task with negative usage count.

### Put here any screenshots or videos (optional)

![Screenshot (403)](https://github.com/gtech-mulearn/mulearn/assets/106170027/282274a3-e204-4bed-9353-1d2efcbe9742)

### Would you like to work on this issue?

None

**Comment by Ansanjohny** [comment]
@vidhya-vjkumar negative use count is allowed...
