### ISSUE TITLE
Search Learning Circles not working

### ISSUE THREAD

**Issue by deepusnath** [gtech-mulearn/mulearn#36]
Search learning circles is not working when it goes from an interest group page. 

**How to replicate the issue**
1. Go to https://learn.mulearn.org/ 
2. Checkout any interest group (Eg. Cyber Security)
3. Click on Search Learning Circles Button
4. Select District. 

The page reloads and goes to a blank page..

**Comment by VinuBalagopalAP** [comment]
Done
