### ISSUE TITLE
[ bug ] : Search does not index terms without spaces

### ISSUE THREAD

**Issue by bijomathewjose** [gtech-mulearn/mulearn#403]
## Description
The search option does not index terms without spaces

## Steps to Reproduce
1. Go to the '/campus-details' page or any page with a search option.
2. Search a name in the list with no space
3. Click Enter button on the keyboard
4. No output is visible

## Expected Behavior
The search option should give results even when the search value has no space .

## Screenshots
![Screenshot 2023-07-05 172131](https://github.com/gtech-mulearn/mulearn/assets/73273702/fb766b76-b072-4791-a52a-2e3ab1ca8a97)
![Screenshot 2023-07-05 172147](https://github.com/gtech-mulearn/mulearn/assets/73273702/8a318bd7-ff62-45d2-8118-47fcc400ceff)
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/c3094a69-0fa1-4f26-88b3-ff5ea7bc2cb1)

## Additional Information
- Browser: Chrome
- Version: 114.0.5735.199 (Official Build) (64-bit)
- Operating System: Windows 11

**Comment by AswinAsok** [comment]
This issue has been fixed.Kindly check the dev-server
