### ISSUE TITLE
[ ux ] : Search bar does not have a clickable search icon

### ISSUE THREAD

**Issue by bijomathewjose** [gtech-mulearn/mulearn#404]
## Description

The search bar on our website does not have a search icon. This makes it difficult for users to initiate a search. According to Hick's law, the time it takes to make a decision increases with the number of choices available. In this case, the user must decide whether to click on the search bar or click enter. This additional decision can take time and effort, leading to frustration and abandonment.

## Steps to reproduce

1. Go to the '/campus-details' page or any page with a search option.
2. Notice that there is no search icon.

## Screenshots
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/1687b3f5-f9e9-4ce6-80c1-e2c473d05d16)
## Details
|Expected behaviour|Current Behaviour| Severity | Priority |
|-|-|---|---|
|A search icon is required and should be clickable. <br/>When clicked, it should initiate a search.| There is no search icon|Medium | Medium |

**Comment by Jenin82** [comment]
issue fixed
