### ISSUE TITLE
[ bug ] : [ URL-shortener :  Create ]-[ wrong-format : short-URL ]  

### ISSUE THREAD

**Issue by bijomathewjose** [gtech-mulearn/mulearn#405]
## Description
Unresponsive URL shortener when the wrong short URL format used

## Steps to Reproduce
1. Go to the '/url-shortener' page 
2. Enter the details Title, Long Url, Short URL 
3. Click on Create button 
4. A red pop with no error message

## Expected Behavior
An error message is expected
The format of the link should be provided as a placeholder/tooltip/etc/...

## Screenshots
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/e4f66e53-c7d0-4444-8af4-64621a88b9fd)

## Additional Information
- Browser: Chrome
- Version: 114.0.5735.199 (Official Build) (64-bit)
- Operating System: Windows 11

**Comment by AswinAsok** [comment]
This issue has been fixed. Kindly check the dev-server.
