### ISSUE TITLE
[ bugs ] : [ Public Profile Switch ]

### ISSUE THREAD

**Issue by bijomathewjose** [gtech-mulearn/mulearn#407]
## Description
1. On updating profile visibility it seems updated, but not getting updated and on reload shows the same private profile again
2. 'Do you want make your profile Public ?" is grammatically incorrect, it should be  'Do you want to make your profile Public ?"
3. On switching back to a private profile, the success response is still ' Now your profile is shareable '

### Issues 1 

1.  Go to the '/profile' page 
2.  Click on the share button
3.  A modal popup is visible, click on the button following 'Do you want make your profile Public ?" which is grey at the moment indicating the profile is private
4.  After the above operation 

- - the switch turns blue indicating the profile view is switched to public
- - the ring around the profile picture turns green indicating the profile is public
- - a successful message response produced 
- - A link and QR code is generated

5. Copy the link and paste it into a new tab
6. The new tab shows the page is still private 
7. On coming back to '/profile' page and reloading we can see that the profile picture circle ring turned back to blue indicating the profile is still  actually private

### Issue 2

1. Go to the '/profile' page 
2. Click on the share button
3. A modal popup is visible,  'Do you want make your profile Public ?"
### Issue 3
1. Go to the '/profile' page 
2. Click on the share button
3. A modal popup is visible, click on the button following 'Do you want make your profile Public ?" which is blue at the moment indicating the profile is private
4.  After the above operation the switch turns blue indicating the profile view is switched to public, click again
5. The success response will be ' Now your profile is shareable '

### Issue 1
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/b08a23bc-7d4e-4514-9bb4-6116d74cddc5)
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/4c034237-183f-4cf3-9974-3a7aa2069c62)
### Issue 2
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/66b502e6-3667-4c03-a341-50224bedfc72)

### Issue 3
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/38c72c0e-359c-4aa4-bea0-6d91d5f8b4ed)

## Expected Behavior
The profile should be updated to public/private according to the state
The grammar should be correct
Correct response for the action taken

## Additional Information
- Browser: Chrome
- Version: 114.0.5735.199 (Official Build) (64-bit)
- Operating System: Windows 11

**Comment by Jovit-Mathew236** [comment]
Fixed switch issue
