### ISSUE TITLE
[ ux ] : Search bar does not have direct approach for clearing the search

### ISSUE THREAD

**Issue by bijomathewjose** [gtech-mulearn/mulearn#408]
## Description

The search bar on our website does not have a cancel/clear icon. Since the search only works with either enter button or clicking the arrow icon, it poses a question on how to clear the search, the user has to find out what he/she should do. This makes it difficult for users to initiate a search. According to Hick's law, the time it takes to make a decision increases with the number of choices available. In this case, the user must decide and find how to clear the search bar . This additional decision can take time and effort, leading to frustration and abandonment.

## Steps to reproduce

1. Go to the '/campus-details' page or any page with a search option.
2. Add value to search bar
3. Notice that there is a no search clear icon.

## Screenshots
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/22e8f65d-cc61-4c30-b160-936685d6a3cc)

## Details
|Expected behaviour|Current Behaviour| Severity | Priority |
|-|-|---|---|
|A clear icon is required. <br/>When clicked, it should clear the search.| There is no clear icon|Medium | Medium |

**Comment by Jenin82** [comment]
ok will work in it
