### ISSUE TITLE
[ bug ] : Download CSV 

### ISSUE THREAD

**Issue by bijomathewjose** [gtech-mulearn/mulearn#409]
## Description
On page load, the initial click on the download csv button does not produce the results 

## Steps to reproduce
1. Load any of the pages below and click the csv button

- /interest-groups
- /organizations
- /tasks
- /manage-users
- /manage-roles
- /district-dashboard

2. Data is loaded from the backend, but the csv is not getting downloaded
3. On the second click, an API called csv is getting downloaded
### First Click
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/eb609e5d-feda-4243-84a1-015aece397d6)
### Second click
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/bb33ea30-086a-42ef-90ef-2ed9982c1ae7)
## Expected Behaviour 
If csv button is clicked, if there is data and a success message on the download 

## Additional Information
- Browser: Chrome
- Version: 114.0.5735.199 (Official Build) (64-bit)
- Operating System: Windows 11

**Comment by AswinAsok** [comment]
This issue has been fixed. Kindly check the dev-server.
