### ISSUE TITLE
[ bug ] : Loading Issue

### ISSUE THREAD

**Issue by bijomathewjose** [gtech-mulearn/mulearn#418]
## Description
When a user logs into the site in a new tab about an hour or half later, or when an existing open tab which was inactive for an hour or half is reloaded, the page just shows loading and errors in the console. This issue is not present if you reload the page again or log in.

## Steps to reproduce

1. Open the site in a new tab.
2. Wait for about an hour or a half.
3. Reload the page.
### Or

1. Login to the site
2. Close the tab but do not log out
3. Open the site after an hour or a half.

## Screenshots
![WhatsApp Image 2023-07-07 at 16 06 03](https://github.com/gtech-mulearn/mulearn/assets/73273702/8f344270-e60e-431e-a58c-1d61b107cd9b)

## Expected behaviour
The page should load contents properly without fault

| Severity | Priority |
|-|-|
|High| High |
## Additional Information
- Browser: Chrome
- Version: Version 114.0.5735.199 (Official Build) (64-bit)
- Operating System: Windows 11

**Comment by Jovit-Mathew236** [comment]
solved the issue at #478
