### ISSUE TITLE
[ bug ] : Incorrect display of level 

### ISSUE THREAD

**Issue by bijomathewjose** [gtech-mulearn/mulearn#423]
## Description
The level provided by Mu Voyage section of the profile page is not correct ,the actual level is shown in the profile to the right of the profile picture

## Steps to reproduce

1. Login to site
2. Open the page '/profile' 
3. Select Mu Voyage section
4. In the Mu Voyage section wrong level is shown

## Screenshots
![image](https://github.com/gtech-mulearn/mulearn/assets/73273702/9b228aca-04d8-4466-bdbe-02af583a1f37)

## Expected Behaviour
Either do not show the level here since the level is already present in the page
Or Correct the level shown there

| Severity | Priority |
|---|---|
| Low |  Low |
## Additional Information

- Browser: Chrome
- Version: Version 114.0.5735.199 (Official Build) (64-bit)
- Operating System: Windows 11

**Comment by Jovit-Mathew236** [comment]
issue solved by #464 this pr
