### ISSUE TITLE
Blog Page

### ISSUE THREAD

**Issue by VinuBalagopalAP** [gtech-mulearn/mulearn#77]
https://www.figma.com/file/gElKnrCpIHt8vQAZZoEW7X/MuLearn-Blog?node-id=1%3A3&t=nVMo9SjKU1X12Fxr-1

**Comment by VinuBalagopalAP** [comment]
https://github.com/gtech-mulearn/mulearn/tree/master/src/Pages/CampusChapters

**Comment by VinuBalagopalAP** [comment]
1. Blog landing page
2. Cards listing
3. Inner blog view with JSON mapping

**Comment by Jovit-Mathew236** [comment]
4. Gig Work
