### ISSUE TITLE
Unexpected Application Error: Falied to Fetch Dynamically Imported Module

### ISSUE THREAD

**Issue by AswinAsok** [gtech-mulearn/mulearn#897]
![image](https://github.com/gtech-mulearn/mulearn/assets/64626875/0035c7b7-7f29-45d8-9b46-351bdfb0299b)

**Comment by adhirajkar3103** [comment]
Please assign me this issue?

**Comment by vishakh-abhayan** [comment]
Please assign me this issue.



> Please assign me this issue?

@adhirajkar3103 , any updates?
